- name: Create Ollama volumes
  community.docker.docker_volume:
    volume_name: "{{ item }}"
  loop:
    - ollama-data

- name: Create Ollama container
  community.docker.docker_container:
    name: "ollama"
    image: ollama/ollama:latest

    volumes:
      - ollama-data:/root/.ollama:rw

    ports: "{{ ollama_ports | default([]) }}"

    networks: "{{ docker_networks }}"
    comparisons: "{{ docker_comparisons }}"
    image_name_mismatch: "{{ docker_image_name_mismatch }}"
    state: "{{ docker_state }}"
    restart_policy: "{{ docker_restart_policy }}"
    pull: "{{ docker_pull }}"

- name: Register Ollama container name
  ansible.builtin.set_fact:
    ollama_container_name: "ollama"
