- name: Create Ollama volumes
  community.docker.docker_volume:
    volume_name: "{{ item }}"
  loop:
    - ollama-data

- name: Create Ollama container
  community.docker.docker_container:
    name: "{{ ollama_container_name }}"
    image: ollama/ollama:latest
    pull: "{{ homelab_docker_pull | default('missing') }}"

    ports:
      - "{{ ollama_port }}:11434"

    volumes:
      - ollama-data:/root/.ollama:rw

    networks:
      - name: "{{ docker_network }}"

    comparisons:
      env: strict
      labels: strict

    image_name_mismatch: recreate

    state: started
    restart_policy: unless-stopped
