- name: Disable pve-enterprise repository
  ansible.builtin.deb822_repository:
    name: pve-enterprise
    types: deb
    uris: https://enterprise.proxmox.com/debian/pve
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: pve-enterprise
    enabled: false

- name: Disable ceph enterprise repository
  ansible.builtin.deb822_repository:
    name: ceph
    types: deb
    uris: "https://enterprise.proxmox.com/debian/ceph-squid }}"
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: enterprise
    enabled: false

- name: Add pve-no-subscription repository
  ansible.builtin.deb822_repository:
    name: pve-no-subscription
    types: deb
    uris: "http://download.proxmox.com/{{ ansible_facts['distribution'] | lower }}/pve"
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: pve-no-subscription

- name: Install packages
  ansible.builtin.apt:
    name: "{{ pve_packages | default([]) }}"

- name: Limit ZFS memory usage to 8GB
  ansible.builtin.copy:
    src: zfs.conf
    dest: /etc/modprobe.d/zfs.conf
    mode: "0644"

- name: Configure mount points
  ansible.posix.mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    state: present
  with_items: "{{ pve_mount_points }}"
  when: pve_mount_points is defined

- name: "Configure NFS exports"
  ansible.builtin.template:
    src: "exports.j2"
    dest: "/etc/exports"
    mode: "0644"
  when: pve_nfs_exports is defined
