- name: Create Grafana volumes
  community.docker.docker_volume:
    volume_name: "{{ item }}"
  loop:
    - grafana-config
    - grafana-data

- name: Create Grafana container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana:latest

    env:
      GF_SECURITY_ADMIN_USER: "{{ grafana_admin_user }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password }}"

    volumes:
      - grafana-config:/etc/grafana:rw
      - grafana-data:/var/lib/grafana:rw

    ports: "{{ grafana_ports | default([]) }}"

    networks: "{{ docker_networks }}"
    comparisons: "{{ docker_comparisons }}"
    image_name_mismatch: "{{ docker_image_name_mismatch }}"
    state: "{{ docker_state }}"
    restart_policy: "{{ docker_restart_policy }}"
    pull: "{{ docker_pull }}"

- name: Register Grafana container name
  ansible.builtin.set_fact:
    grafana_container_name: "grafana"
