- name: Create /etc/mailrise
  ansible.builtin.file:
    path: /etc/mailrise
    state: directory
    mode: "0755"

- name: Configure Mailrise
  ansible.builtin.template:
    src: "mailrise.yml.j2"
    dest: /etc/mailrise/mailrise.yml
    mode: "0644"
  notify: Restart Mailrise

- name: Create Mailrise container
  community.docker.docker_container:
    name: mailrise
    image: yoryan/mailrise:latest

    volumes:
      - /etc/mailrise/mailrise.yml:/etc/mailrise.conf:ro

    ports: "{{ mailrise_ports | default([]) }}"

    networks: "{{ docker_networks }}"
    comparisons: "{{ docker_comparisons }}"
    image_name_mismatch: "{{ docker_image_name_mismatch }}"
    state: "{{ docker_state }}"
    restart_policy: "{{ docker_restart_policy }}"
    pull: "{{ docker_pull }}"

- name: Register Mailrise container name
  ansible.builtin.set_fact:
    mailrise_container_name: "mailrise"
