- name: Create /etc/searxng
  ansible.builtin.file:
    path: /etc/searxng
    state: directory
    mode: "0755"

- name: Configure SearXNG
  ansible.builtin.template:
    src: settings.yml.j2
    dest: /etc/searxng/settings.yml
    mode: "0644"
  notify: Restart SearXNG

- name: Configure SearXNG limiter
  ansible.builtin.template:
    src: limiter.toml.j2
    dest: /etc/searxng/limiter.toml
    mode: "0644"
  notify: Restart SearXNG

- name: Create SearXNG volumes
  community.docker.docker_volume:
    name: searxng-redis-data

- name: Create Redis container
  community.docker.docker_container:
    name: searxng-redis
    image: docker.io/valkey/valkey:8-alpine
    pull: "{{ homelab_docker_pull | default('missing') }}"

    ports:
      - "{{ searxng_redis_port }}:6379"

    volumes:
      - searxng-redis-data:/data:rw

    command: valkey-server --save 30 1 --loglevel warning

    networks:
      - name: "{{ docker_network }}"

    comparisons:
      env: strict
      labels: strict

    image_name_mismatch: recreate

    state: started
    restart_policy: unless-stopped

- name: Create SearXNG container
  community.docker.docker_container:
    name: "{{ searxng_container_name }}"
    image: searxng/searxng:latest
    pull: "{{ homelab_docker_pull | default('missing') }}"

    ports:
      - "{{ searxng_port }}:8080"

    env:
      SEARXNG_BASE_URL: "https://searxng.{{ ansible_domain }}"
      SEARXNG_REDIS_URL: "redis://searxng-redis:{{ searxng_redis_port }}"

    volumes:
      - /etc/searxng/settings.yml:/etc/searxng/settings.yml
      - /etc/searxng/limiter.toml:/etc/searxng/limiter.toml

    networks:
      - name: "{{ docker_network }}"

    comparisons:
      env: strict
      labels: strict

    image_name_mismatch: recreate

    state: started
    restart_policy: unless-stopped
