- name: Create /etc/zigbee2mqtt
  ansible.builtin.file:
    path: /etc/zigbee2mqtt
    state: directory
    mode: "0755"

- name: Configure Zigbee2MQTT
  ansible.builtin.template:
    src: zigbee2mqtt.yml.j2
    dest: /etc/zigbee2mqtt/configuration.yaml
    mode: "0644"
  notify:
    - Restart Zigbee2MQTT

- name: Create Zigbee2MQTT container
  community.docker.docker_container:
    name: zigbee2mqtt
    image: koenkk/zigbee2mqtt

    env:
      TZ: "{{ timezone | default('UTC') }}"
      Z2M_WATCHDOG: default

    volumes:
      - /etc/zigbee2mqtt:/app/data:rw

    ports: "{{ z2m_ports | default([]) }}"

    networks: "{{ docker_networks }}"
    comparisons: "{{ docker_comparisons }}"
    image_name_mismatch: "{{ docker_image_name_mismatch }}"
    state: "{{ docker_state }}"
    restart_policy: "{{ docker_restart_policy }}"
    pull: "{{ docker_pull }}"

- name: Register Zigbee2MQTT container name
  ansible.builtin.set_fact:
    z2m_container_name: "zigbee2mqtt"
