- name: Create Uptime Kuma volumes
  community.docker.docker_volume:
    volume_name: "{{ item }}"
  loop:
    - uptime_kuma-data

- name: Create Uptime Kuma container
  community.docker.docker_container:
    name: uptime-kuma
    image: louislam/uptime-kuma:latest

    volumes:
      - uptime_kuma-data:/app/data:rw

    labels:
      traefik.enable: "true"
      traefik.http.routers.uptime.rule: "Host(`uptime.{{ ansible_domain }}`)"
      traefik.http.routers.uptime.service: "uptime"
      traefik.http.services.uptime.loadbalancer.server.port: "3001"

    ports: "{{ uptime_kuma_ports | default([]) }}"

    networks: "{{ docker_networks }}"
    comparisons: "{{ docker_comparisons }}"
    image_name_mismatch: "{{ docker_image_name_mismatch }}"
    state: "{{ docker_state }}"
    restart_policy: "{{ docker_restart_policy }}"
    pull: "{{ docker_pull }}"

- name: Register Uptime Kuma container name
  ansible.builtin.set_fact:
    uptime_kuma_container_name: "uptime-kuma"
