- name: Create /etc/prometheus
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    mode: "0755"

- name: Configure Prometheus
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    mode: "0644"
  notify:
    - Restart Prometheus

- name: Configure Prometheus web
  ansible.builtin.template:
    src: web.yml.j2
    dest: /etc/prometheus/web.yml
    mode: "0644"
  notify:
    - Restart Prometheus

- name: Create Prometheus volumes
  community.docker.docker_volume:
    volume_name: "{{ item }}"
  loop:
    - prometheus-data

- name: Create Prometheus container
  community.docker.docker_container:
    name: prometheus
    image: prom/prometheus:latest

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time={{ prometheus_storage_retention }}"
      - "--web.config.file=/etc/prometheus/web.yml"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"

    volumes:
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /etc/prometheus/web.yml:/etc/prometheus/web.yml:ro
      - prometheus-data:/prometheus:rw

    ports: "{{ prometheus_ports | default([]) }}"

    networks: "{{ docker_networks }}"
    comparisons: "{{ docker_comparisons }}"
    image_name_mismatch: "{{ docker_image_name_mismatch }}"
    state: "{{ docker_state }}"
    restart_policy: "{{ docker_restart_policy }}"
    pull: "{{ docker_pull }}"

- name: Register Prometheus container name
  ansible.builtin.set_fact:
    prometheus_container_name: "prometheus"
