- name: Create Tika container
  community.docker.docker_container:
    name: "tika"
    image: apache/tika:latest-full

    ports: "{{ tika_ports | default([]) }}"

    networks: "{{ docker_networks }}"
    comparisons: "{{ docker_comparisons }}"
    image_name_mismatch: "{{ docker_image_name_mismatch }}"
    state: "{{ docker_state }}"
    restart_policy: "{{ docker_restart_policy }}"
    pull: "{{ docker_pull }}"

- name: Register Tika container name
  ansible.builtin.set_fact:
    tika_container_name: "tika"
