- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - gpg
      - python3-debian

- name: Add Proxmox Backup Server repository
  ansible.builtin.deb822_repository:
    name: pbs
    types: deb
    uris: "http://download.proxmox.com/{{ ansible_facts['distribution'] | lower }}/pbs"
    suites: "{{ ansible_facts['distribution_release'] }}"
    components:
      - pbs-no-subscription
    signed_by: "https://enterprise.proxmox.com/{{ ansible_facts['distribution'] | lower }}/proxmox-release-{{ ansible_facts['distribution_release'] }}.gpg"

- name: Install Proxmox Backup Server
  ansible.builtin.apt:
    name: proxmox-backup-server
