- name: Create Open Web UI volumes
  community.docker.docker_volume:
    volume_name: "{{ item }}"
  loop:
    - openwebui-data

- name: Create Open Web UI container
  community.docker.docker_container:
    name: "openwebui"
    image: ghcr.io/open-webui/open-webui:main

    env:
      WEBUI_URL: "https://openwebui.{{ ansible_domain }}"

      ENABLE_OLLAMA_API: "{{ openwebui_enable_ollama_api | default('true') }}"
      OLLAMA_BASE_URL: "http://{{ ollama_container_name }}:11434"

      ENABLE_OPENAI_API: "{{ openwebui_enable_openai_api | default('true') }}"
      OPENAI_API_BASE_URL: "{{ openwebui_openai_api_base_url | default('https://api.openai.com/v1') }}"
      OPENAI_API_KEY: "{{ openwebui_openai_api_key }}"

      RAG_WEB_SEARCH_ENGINE: searxng
      SEARXNG_QUERY_URL: http://{{ searxng_container_name }}:8080/search?q=<query>

      CONTENT_EXTRACTION_ENGINE: tika
      TIKA_SERVER_URL: "http://{{ tika_container_name }}:9998"

    volumes:
      - openwebui-data:/app/backend/data:rw

    ports: "{{ openwebui_ports | default([]) }}"

    networks: "{{ docker_networks }}"
    comparisons: "{{ docker_comparisons }}"
    image_name_mismatch: "{{ docker_image_name_mismatch }}"
    state: "{{ docker_state }}"
    restart_policy: "{{ docker_restart_policy }}"
    pull: "{{ docker_pull }}"

- name: Register Open Web UI container name
  ansible.builtin.set_fact:
    openwebui_container_name: "openwebui"
